version: '3.8'

services:
  # ================================
  # Nginx Reverse Proxy
  # ================================
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./client_nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx_logs:/var/log/nginx
    depends_on:
      - frontend
      - backend
    networks:
      - helpdesk_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ================================
  # Frontend Service
  # ================================
  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile
      target: production
    ports:
      - "3011:3011"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://e2425-wads-l4acg6-server.csbihub.id/api
      - NEXT_PUBLIC_WS_URL=wss://e2425-wads-l4acg6-server.csbihub.id
    volumes:
      - frontend_data:/app/.next
    networks:
      - helpdesk_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3011"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ================================
  # Backend Service
  # ================================
  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile
      target: production
    ports:
      - "8000:8000"
    environment:
      # Database Configuration (matching .env)
      - MONGODB_URL=mongodb://e2425-wads-l4acg6:hoch22uc@mongo:27018/?authSource=e2425-wads-l4acg6
      - DATABASE_NAME=e2425-wads-l4acg6
      
      # JWT Configuration
      - SECRET_KEY=your_super_secret_key_here_change_in_production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      
      # Redis Configuration
      - REDIS_URL=redis://redis:6379
      
      # Application Configuration
      - DEBUG=false
      - HOST=0.0.0.0
      - PORT=8000
      - CORS_ORIGINS=["https://e2425-wads-l4acg6-client.csbihub.id","http://localhost","https://localhost","http://helpdesk.local"]
      
      # File Upload Configuration
      - MAX_FILE_SIZE=5242880
      - UPLOAD_DIR=/app/uploads
    volumes:
      - uploads_data:/app/uploads
    networks:
      - helpdesk_network
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ================================
  # MongoDB Database
  # ================================
  mongo:
    image: mongo:7.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=e2425-wads-l4acg6
      - MONGO_INITDB_ROOT_PASSWORD=hoch22uc
      - MONGO_INITDB_DATABASE=e2425-wads-l4acg6
    volumes:
      - mongo_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27018:27017"
    networks:
      - helpdesk_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ================================
  # Redis Cache
  # ================================
  redis:
    image: redis:7.0-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - helpdesk_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ================================
  # Database Management (Optional)
  # ================================
  mongo-express:
    image: mongo-express:1.0.2
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=e2425-wads-l4acg6
      - ME_CONFIG_MONGODB_ADMINPASSWORD=hoch22uc
      - ME_CONFIG_MONGODB_URL=mongodb://e2425-wads-l4acg6:hoch22uc@mongo:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    ports:
      - "8081:8081"
    networks:
      - helpdesk_network
    depends_on:
      - mongo
    profiles:
      - tools

# ================================
# Named Volumes
# ================================
volumes:
  mongo_data:
    driver: local
  redis_data:
    driver: local
  uploads_data:
    driver: local
  frontend_data:
    driver: local
  nginx_logs:
    driver: local

# ================================
# Network Configuration
# ================================
networks:
  helpdesk_network:
    driver: bridge 