version: '3.8'

services:
  # ================================
  # Development Services
  # ================================
  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile
      target: development
    ports:
      - "3011:3011"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
      - /app/frontend/.next
    networks:
      - helpdesk_network
    depends_on:
      - backend
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile
      target: development
    ports:
      - "8000:8000"
    environment:
      # Database Configuration (matching .env)
      - MONGODB_URL=mongodb://e2425-wads-l4acg6:hoch22uc@mongo:27018/?authSource=e2425-wads-l4acg6
      - DATABASE_NAME=e2425-wads-l4acg6
      
      # JWT Configuration
      - SECRET_KEY=dev_secret_key_change_in_production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440  # 24 hours for development
      
      # Redis Configuration
      - REDIS_URL=redis://redis:6379
      
      # Development Configuration
      - DEBUG=true
      - HOST=0.0.0.0
      - PORT=8000
      - CORS_ORIGINS=["http://localhost:3011","http://127.0.0.1:3011","http://localhost:3000","https://e2425-wads-l4acg6-client.csbihub.id"]
      
      # File Upload Configuration
      - MAX_FILE_SIZE=10485760  # 10MB for development
      - UPLOAD_DIR=/app/uploads
    volumes:
      - ./backend:/app/backend
      - ./uploads:/app/uploads
      - /app/backend/__pycache__
    networks:
      - helpdesk_network
    depends_on:
      - mongo
      - redis
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # ================================
  # Database Services
  # ================================
  mongo:
    image: mongo:7.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=e2425-wads-l4acg6
      - MONGO_INITDB_ROOT_PASSWORD=hoch22uc
      - MONGO_INITDB_DATABASE=e2425-wads-l4acg6
    volumes:
      - mongo_dev_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27018:27017"
    networks:
      - helpdesk_network

  redis:
    image: redis:7.0-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_dev_data:/data
    ports:
      - "6379:6379"
    networks:
      - helpdesk_network

  # ================================
  # Database Management Tools
  # ================================
  mongo-express:
    image: mongo-express:1.0.2
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=e2425-wads-l4acg6
      - ME_CONFIG_MONGODB_ADMINPASSWORD=hoch22uc
      - ME_CONFIG_MONGODB_URL=mongodb://e2425-wads-l4acg6:hoch22uc@mongo:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    ports:
      - "8081:8081"
    networks:
      - helpdesk_network
    depends_on:
      - mongo

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8082:8081"
    networks:
      - helpdesk_network
    depends_on:
      - redis

# ================================
# Development Volumes
# ================================
volumes:
  mongo_dev_data:
    driver: local
  redis_dev_data:
    driver: local

# ================================
# Network Configuration
# ================================
networks:
  helpdesk_network:
    driver: bridge 