version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: helpdesk_postgres
    environment:
      POSTGRES_USER: helpdesk_user
      POSTGRES_PASSWORD: helpdesk_password
      POSTGRES_DB: helpdesk_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U helpdesk_user -d helpdesk_db"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    container_name: helpdesk_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # FastAPI Application (optional - for production)
  api:
    build: .
    container_name: helpdesk_api
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://helpdesk_user:helpdesk_password@postgres:5432/helpdesk_db
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    profiles:
      - full

volumes:
  postgres_data:
  redis_data: 